name: Build and Release AutoLoop Manager

on:
  push:
    tags:
      - "v*"  # Запускать workflow при пуше тегов
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: pip install pyinstaller pyqt5

    - name: Build EXE
      run: pyinstaller --noconsole --onefile main.py

    - name: Upload EXE to artifacts
      uses: actions/upload-artifact@v3.1
      with:
        name: AutoLoopManager
        path: dist/main.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: AutoLoopManager

    - name: Create Release
      uses: softprops/action-gh-release@v1.1.0
      with:
        files: dist/main.exe
        tag_name: ${{ github.ref_name }}  # Указывает тег, с которым был вызван workflow
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
