name: Build and Release AutoLoop Manager

on:
  push:
    tags:
      - "v*"  # Запускать workflow при пуше тегов
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Название тега для релиза (например, v1.0)"
        required: false

permissions:
  contents: write  # Разрешение на запись для создания релизов

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: pip install pyinstaller pyqt5

    - name: Build EXE
      run: pyinstaller --noconsole --onefile main.py

    - name: List files in dist
      run: dir dist  # Проверка содержимого директории dist

    - name: Upload EXE to artifacts
      uses: actions/upload-artifact@v3
      with:
        name: AutoLoopManager
        path: dist/main.exe

  release:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: AutoLoopManager
        path: .

    - name: Verify downloaded files
      run: dir  # Проверяем скачанные файлы

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: main.exe
        tag_name: ${{ github.ref_name || github.event.inputs.tag_name }}
        name: "Release ${{ github.ref_name || github.event.inputs.tag_name }}"
        body: "Автоматический релиз версии ${{ github.ref_name || github.event.inputs.tag_name }}."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
